export const endpoints = {
  login: "/auth/login",
  register: "/auth/register",
  overview: "/dashboard/overview",
  users: "/users",
  notificationsMe: "/notifications/me",
  notificationsUnreadCount: "/notifications/me/unread-count",
  notificationsReadAll: "/notifications/me/read-all",
  notificationsRead: (id) => `/notifications/${id}/read`,
  notificationsSettings: "/notifications/settings",
  notificationsRunNow: "/notifications/run-reminders",
  appSettings: "/settings/app",

  properties: "/properties",
  propertyById: (id) => `/properties/${id}`,
  propertyAddImages: (id) => `/properties/${id}/images`,
  propertyListingSettings: (id) => `/properties/${id}/listing-settings`,
  propertyPortalExportCsv: "/properties/portal-export/csv",
  websiteListings: "/properties/website-listings",
  inventoryTowers: "/inventory/towers",
  inventoryFloors: "/inventory/floors",
  inventoryUnits: "/inventory/units",
  documents: "/documents",
  leads: "/leads",
  leadById: (id) => `/leads/${id}`,
  leadDuplicateCheck: "/leads/duplicates/check",
  leadImportMapped: "/leads/import/mapped",
  leadNotes: (id) => `/leads/${id}/notes`,
  leadCalls: (id) => `/leads/${id}/calls`,
  leadAssign: (id) => `/leads/${id}/assign`,
  leadStage: (id) => `/leads/${id}/stage`,
  leadScore: (id) => `/leads/${id}/score`,
  leadFollowups: "/leads/followups/tasks",
  leadEscalateStale: "/leads/escalate/stale",
  customers: "/customers",
  customerKyc: (id) => `/customers/${id}/kyc`,
  customerFamily: (id) => `/customers/${id}/family`,
  customerSuggestions: (id) => `/customers/${id}/suggestions`,
  tenants: "/tenants",
  tenantVerificationNotes: (id) => `/tenants/${id}/verification-notes`,
  owners: "/owners",
  ownerProperties: (id) => `/owners/${id}/properties`,
  bookings: "/bookings",
  bookingConfirm: (id) => `/bookings/${id}/confirm`,
  bookingConfirmationPdf: (id) => `/bookings/${id}/confirmation-pdf`,
  bookingCancelRequest: (id) => `/bookings/${id}/cancel/request`,
  bookingCancelApprove: (id) => `/bookings/${id}/cancel/approve`,
  bookingRefundRequest: (id) => `/bookings/${id}/refund/request`,
  bookingRefundApprove: (id) => `/bookings/${id}/refund/approve`,
  bookingRefundProcess: (id) => `/bookings/${id}/refund/process`,
  bookingTokenReceipt: (id) => `/bookings/${id}/token-receipt`,
  siteVisits: "/site-visits",
  siteVisitOutcome: (id) => `/site-visits/${id}/outcome`,
  agreementTemplates: "/agreements/templates",
  agreementTransactions: "/agreements/transactions",
  agreementAutofill: (id) => `/agreements/transactions/${id}/autofill`,
  agreementChecklistByType: "/agreements/checklist",
  agreementChecklist: (id) => `/agreements/transactions/${id}/checklist`,
  agreementChecklistItem: (id, itemId) => `/agreements/transactions/${id}/checklist/${itemId}`,
  agreementTitleStatus: (id) => `/agreements/transactions/${id}/title-status`,
  agreementLegalApproval: (id) => `/agreements/transactions/${id}/legal-approval`,
  agreementReview: (id) => `/agreements/transactions/${id}/review`,
  agreementReviewReport: (id) => `/agreements/transactions/${id}/review-report`,
  agreementReadyRegistration: (id) => `/agreements/transactions/${id}/ready-for-registration`,
  agreementFinalCompleteness: (id) => `/agreements/transactions/${id}/final-completeness`,
  agreementRegistration: (id) => `/agreements/transactions/${id}/registration`,
  agreementEsignPlaceholder: (id) => `/agreements/transactions/${id}/esign-placeholder`,
  rentalContracts: "/rentals/contracts",
  rentalSchedules: "/rentals/schedules",
  rentalCollect: (id) => `/rentals/schedules/${id}/collect`,
  rentalReceipt: (id) => `/rentals/schedules/${id}/receipt`,
  rentalOverdueRun: "/rentals/schedules/run-overdue-check",
  maintenanceTickets: "/rentals/maintenance/tickets",
  maintenanceAssignVendor: (id) => `/rentals/maintenance/tickets/${id}/assign-vendor`,
  maintenanceStatus: (id) => `/rentals/maintenance/tickets/${id}/status`,
  maintenancePaymentRequest: (id) => `/rentals/maintenance/tickets/${id}/payment-request`,
  maintenanceSla: "/rentals/maintenance/sla-report",
  rentalMoveChecklists: "/rentals/tenant-ops/move-checklists",
  rentalMoveChecklistById: (id) => `/rentals/tenant-ops/move-checklists/${id}`,
  rentalComplaints: "/rentals/tenant-ops/complaints",
  rentalComplaintById: (id) => `/rentals/tenant-ops/complaints/${id}`,
  inspections: "/rentals/inspections",
  ownerMonthlyStatement: (ownerId) => `/rentals/owners/${ownerId}/monthly-statement`,
  rentalPropertyProfitability: "/rentals/properties/profitability",
  accountsCoa: "/accounts/coa",
  accountsJournals: "/accounts/journals",
  accountsJournalLines: (id) => `/accounts/journals/${id}/lines`,
  accountsPl: "/accounts/reports/pl",
  accountsCashflow: "/accounts/reports/cashflow",
  accountsArAp: "/accounts/reports/ar-ap",
  commissionAgents: "/commissions/agents",
  commissionRules: "/commissions/rules",
  commissionSplits: "/commissions/splits",
  commissionSplitApprove: (id) => `/commissions/splits/${id}/approve`,
  commissionSplitPaid: (id) => `/commissions/splits/${id}/paid`,
  commissionPayouts: "/commissions/payouts",
  commissionPayoutApprove: (id) => `/commissions/payouts/${id}/approve`,
  commissionPayoutPaid: (id) => `/commissions/payouts/${id}/paid`,
  commissionDashboard: "/commissions/dashboard",
  invoices: "/billing/invoices",
  invoicePayments: (id) => `/billing/invoices/${id}/payments`,
  invoiceExportPdf: (id) => `/billing/invoices/${id}/export-pdf`,
  invoiceSend: (id) => `/billing/invoices/${id}/send`,
  billingNotes: "/billing/notes",
  reportsSalesFunnel: "/reports/sales-funnel",
  reportsRentDues: "/reports/rent-dues",
  reportsCampaignPerformance: "/reports/campaign-performance",
  reportsCampaignSpend: "/reports/campaign-spend",
  reportsAnalyticsSummary: "/reports/analytics/summary",
  reportsAnalyticsExport: "/reports/analytics/export",
};
