export const ROLES = {
  ADMIN: "Admin",
  SALES_MANAGER: "Sales Manager",
  SALES_AGENT: "Sales Agent",
  ACCOUNTS: "Accounts",
  LEGAL: "Legal",
  PROPERTY_MANAGER: "Property Manager",
};

export const PERMISSIONS = {
  // User & Role management
  USER_MANAGE: "user:manage",
  USER_CREATE: "user:create",
  USER_UPDATE: "user:update",
  USER_DEACTIVATE: "user:deactivate",
  USER_LOCK_UNLOCK: "user:lock_unlock",
  USER_RESET_PASSWORD: "user:reset_password",
  ROLE_ASSIGN: "role:assign",
  PERMISSION_ASSIGN: "permission:assign",

  // Master settings
  MASTER_SETTINGS_MANAGE: "master:manage",
  MASTER_PROPERTY_CONFIG: "master:property_config",
  MASTER_LEAD_CONFIG: "master:lead_config",
  MASTER_TAX_CONFIG: "master:tax_config",
  MASTER_DOC_CATEGORY_CONFIG: "master:doc_category_config",

  // Properties
  PROPERTY_READ: "property:read",
  PROPERTY_CREATE: "property:create",
  PROPERTY_WRITE: "property:write",
  PROPERTY_DELETE: "property:delete",
  PROPERTY_APPROVE: "property:approve",
  PROPERTY_MEDIA_UPLOAD: "property:media_upload",
  INVENTORY_MANAGE: "inventory:manage",
  DOCUMENT_VAULT_READ: "document_vault:read",

  // Leads
  LEAD_READ: "lead:read",
  LEAD_WRITE: "lead:write",
  LEAD_EXPORT: "lead:export",
  LEAD_REASSIGN: "lead:reassign",
  LEAD_OVERRIDE_STAGE: "lead:override_stage",
  LEAD_SCORE_OVERRIDE: "lead:score_override",
  LEAD_MERGE: "lead:merge",
  FOLLOWUP_MANAGE: "followup:manage",
  STALE_LEAD_ESCALATE: "stale_lead:escalate",

  // Customers/Tenants
  CUSTOMER_READ: "customer:read",
  CUSTOMER_WRITE: "customer:write",
  TENANT_READ: "tenant:read",
  TENANT_WRITE: "tenant:write",

  // Bookings
  BOOKING_READ: "booking:read",
  BOOKING_WRITE: "booking:write",
  BOOKING_APPROVE: "booking:approve",
  CANCELLATION_APPROVE: "cancellation:approve",
  REFUND_APPROVE: "refund:approve",
  COMMISSION_APPROVE: "commission:approve",

  // Legal
  AGREEMENT_READ: "agreement:read",
  AGREEMENT_WRITE: "agreement:write",
  TITLE_VERIFY: "title:verify",

  // Billing/Accounts
  BILLING_READ: "billing:read",
  BILLING_WRITE: "billing:write",
  ACCOUNTS_READ: "accounts:read",
  ACCOUNTS_WRITE: "accounts:write",
  COMMISSION_READ: "commission:read",
  COMMISSION_WRITE: "commission:write",
  RENT_READ: "rent:read",
  RENT_WRITE: "rent:write",
  MAINTENANCE_MANAGE: "maintenance:manage",
  INSPECTION_MANAGE: "inspection:manage",
  OWNER_STATEMENT_READ: "owner_statement:read",

  // Reports
  REPORT_READ: "report:read",
  REPORT_EXPORT: "report:export",
  ANALYTICS_FULL: "analytics:full",
  DATA_EXPORT: "data:export",

  // Audit
  AUDIT_READ: "audit:read",
};

export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: Object.values(PERMISSIONS),
  [ROLES.SALES_MANAGER]: [
    PERMISSIONS.PROPERTY_READ, PERMISSIONS.PROPERTY_WRITE, PERMISSIONS.PROPERTY_MEDIA_UPLOAD,
    PERMISSIONS.LEAD_READ, PERMISSIONS.LEAD_WRITE, PERMISSIONS.LEAD_EXPORT,
    PERMISSIONS.LEAD_REASSIGN, PERMISSIONS.LEAD_OVERRIDE_STAGE, PERMISSIONS.LEAD_SCORE_OVERRIDE, PERMISSIONS.LEAD_MERGE,
    PERMISSIONS.FOLLOWUP_MANAGE, PERMISSIONS.STALE_LEAD_ESCALATE,
    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.BOOKING_READ, PERMISSIONS.BOOKING_WRITE, PERMISSIONS.BOOKING_APPROVE, PERMISSIONS.CANCELLATION_APPROVE, PERMISSIONS.REFUND_APPROVE,
    PERMISSIONS.REPORT_READ, PERMISSIONS.REPORT_EXPORT,
  ],
  [ROLES.SALES_AGENT]: [
    PERMISSIONS.PROPERTY_READ, PERMISSIONS.PROPERTY_MEDIA_UPLOAD,
    PERMISSIONS.LEAD_READ, PERMISSIONS.LEAD_WRITE,
    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.BOOKING_READ, PERMISSIONS.BOOKING_WRITE,
  ],
  [ROLES.ACCOUNTS]: [
    PERMISSIONS.PROPERTY_READ,
    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.BOOKING_READ,
    PERMISSIONS.BILLING_READ, PERMISSIONS.BILLING_WRITE,
    PERMISSIONS.ACCOUNTS_READ, PERMISSIONS.ACCOUNTS_WRITE,
    PERMISSIONS.RENT_READ,
    PERMISSIONS.REPORT_READ, PERMISSIONS.REPORT_EXPORT,
  ],
  [ROLES.LEGAL]: [
    PERMISSIONS.AGREEMENT_READ, PERMISSIONS.AGREEMENT_WRITE,
    PERMISSIONS.TITLE_VERIFY,
    PERMISSIONS.PROPERTY_READ, PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.REPORT_READ,
  ],
  [ROLES.PROPERTY_MANAGER]: [
    PERMISSIONS.PROPERTY_READ, PERMISSIONS.PROPERTY_WRITE, PERMISSIONS.PROPERTY_MEDIA_UPLOAD,
    PERMISSIONS.CUSTOMER_READ, PERMISSIONS.CUSTOMER_WRITE,
    PERMISSIONS.TENANT_READ, PERMISSIONS.TENANT_WRITE,
    PERMISSIONS.RENT_READ, PERMISSIONS.RENT_WRITE, PERMISSIONS.MAINTENANCE_MANAGE, PERMISSIONS.INSPECTION_MANAGE, PERMISSIONS.OWNER_STATEMENT_READ,
    PERMISSIONS.REPORT_READ,
  ],
};
